name: fairmq-ex-multiple-channels-sink
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind: []
properties:
  severity: trace
  color: false
command:
  env: []
  shell: true
  arguments: []
  value: >-
    eval `aliswmod load FairMQ Control-OCCPlugin` &&
    fairmq-ex-multiple-channels-sink
