name: fairmq-ex-1-n-1-sink
control:
  mode: fairmq
wants:
  cpu: 0.1
  memory: 128
bind:
- name: "data2"
  type: "pull"
  sndBufSize: 1000
  rcvBufSize: 1000
  rateLogging: 0
properties:
  severity: trace
  color: false
command:
  env: []
  shell: true
  arguments: []
  value: >-
    eval `aliswmod load FairMQ Control-OCCPlugin` &&
    fairmq-ex-1-n-1-sink
