name: mft-decoder-mft-stf-decoder
defaults:
  log_task_output: none
  _module_cmdline: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-itsmft-stf-decoder-workflow
  _plain_cmdline: >-
    source /etc/profile.d/o2.sh && {{ len(extra_env_vars)>0 ? 'export ' + extra_env_vars + ' &&' : '' }} {{ dpl_command }} | o2-itsmft-stf-decoder-workflow
control:
  mode: "fairmq"
wants:
  cpu: 0.01
  memory: 1
bind:
  - name: from_mft-stf-decoder_to_dpl-output-proxy
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
    sndBufSize: 4
    rcvBufSize: 4
command:
  shell: true
  log: "{{ log_task_output }}"
  env: ["O2_DETECTOR={{ detector }}"]
  user: "{{ user }}"
  value: "{{ len(modulepath)>0 ? _module_cmdline : _plain_cmdline }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'{{ session_id }}'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--resources-monitoring"
    - "'{{ resources_monitoring }}'"
    - "--id"
    - "'mft-stf-decoder'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--configKeyValues"
    - "'MFTClustererParam.noiseFilePath=/tmp/_DUMMY_;MFTClustererParam.dictFilePath=/tmp/_DUMMY_'"
    - "--dataspec"
    - "''"
    - "--digits"
    - "--early-forward-policy"
    - "'never'"
    - "--fairmq-ipc-prefix"
    - "'@'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'4'"
    - "--fairmq-send-buffer-size"
    - "'4'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--labels"
    - "''"
    - "--no-clusters"
    - "--pipeline"
    - "''"
    - "--readers"
    - "'1'"
    - "--report-dds-collection-index"
    - "-1"
    - "--runmft"
    - "--severity"
    - "'info'"
    - "--shm-allocation"
    - "'rbtree_best_fit'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-mlock-segment-on-creation"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--spawners"
    - "'1'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--timeframes-rate-limit"
    - "'0'"
    - "--timeframes-rate-limit-ipcid"
    - "-1"
    - "--workflow-suffix"
    - "''"
    - "--decoder-verbosity"
    - "'0'"
    - "--nthreads"
    - "'1'"
