name: o2-roc-ctp-emulator
defaults:
  user: flp
  roc_id: "#0"
  roc_trigger_mode: "continuous"
control:
  mode: basic
wants:
  cpu: 0.01
  memory: 3
command:
  shell: true
  user: "{{ user }}"
  arguments:
    - "--id={{roc_id}}"
    - "--trigger-mode"
    - "{{roc_trigger_mode}}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load ReadoutCard` &&
    o2-roc-ctp-emulator
