name: odc-shim
defaults:
  odc_hostname: localhost
  odc_port: "50051"
  user: flp
  odc_topology_path: /etc/o2.d/odc/ex-dds-topology-infinite.xml
control:
  mode: direct
wants:
  cpu: 0.01
  memory: 3
properties: {}
command:
  env:
    - ODC_TOPOLOGY={{ odc_topology_path }}
    - O2_SYSTEM=ECS
  shell: true
  user: "{{ user }}"
  arguments:
    - --odcHost
    - "{{odc_hostname}}"
    - --odcPort
    - "{{odc_port}}"
    - --verbose
  value: >-
    eval `aliswmod load Control-Core Control-OCCPlugin` &&
    o2-aliecs-odc-shim
