name: readout-qc-check-runner
defaults:
  qc_config_uri: json:///etc/flp.d/qc/readout_to_daqtask.json
  user: flp
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_QC-CHECK-RUNNER-Q4H0_to_internal-dpl-global-binary-file-sink"
    type: "push"
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load QualityControl Control-OCCPlugin` &&
    cat {{dpl_config}}| o2-qc
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--config"
    - "{{qc_config_uri}}"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "QC-CHECK-RUNNER-Q4H0"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--severity"
    - "debug"
    - "--shm-monitor false"
