name: readout # read by workflow
defaults:
  readout_cfg_uri: "consul-ini://{{ consul_endpoint }}/o2/components/readout/ANY/any/readout-standalone-{{ task_hostname }}"
  user: flp
  log_task_output: none
control:
  mode: direct
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: readout
    type: push
    rateLogging: "1"
    addressing: ipc
    transport: shmem
properties: {}
command: 
  env: []
  log: "{{ log_task_output }}"
  shell: true
  user: "{{ user }}"
  arguments:
    - "{{ readout_cfg_uri }}"
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load Readout Control-OCCPlugin &&
    o2-readout-exe
