name: stfbuilder
control:
  mode: fairmq
defaults:
  rdh_version: "6"
  user: flp
  fmq_severity: info
  fmq_verbosity: high
  detector: "{{detector}}"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: dpl-chan
    type: push
    rateLogging: "1"
    transport: shmem
    addressing: ipc
    sndBufSize: "1"
command:
  env: []
  shell: true
  user: "{{ user }}"
  value: >-
    eval `aliswmod load DataDistribution Control-OCCPlugin` &&
    StfBuilder
  arguments:
    - "--detector"
    - "{{detector}}"
    - "--dpl-channel-name=dpl-chan"
    - "--severity={{ fmq_severity }}"
    - "--verbosity={{ fmq_verbosity }}"
    - "--detector-rdh"
    - "{{ rdh_version }}"
