name: stfb-internal-dpl-global-binary-file-sink
defaults:
  stfb_dataspec: "B:TST/RAWDATA"
  user: flp
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
connect:
  - name: from_QC-CHECK-RUNNER-QcCheck_to_internal-dpl-global-binary-file-sink
    type: pull
    rateLogging: "60"
command:
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load QualityControl Control-OCCPlugin &&
    cat {{dpl_config}} | o2-dpl-raw-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_dpl_url }}"
    - "--id"
    - "internal-dpl-global-binary-file-sink"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "{{ stfb_dataspec }}"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--outfile"
    - "/dev/null"
    - "--shm-monitor false"
    - "--infologger-severity"
    - "{{infologger_severity}}"
    - "--infologger-mode"
    - "{{infologger_mode}}"
