name: stfb-raw-proxy-tof
defaults:
  user: flp
  fmq_severity: info
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_tof-compressor-0
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-1
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-2
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-3
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load O2 Control-OCCPlugin` &&
    cat {{dpl_config}} | o2-dpl-raw-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_tof_url }}"
    - "--id"
    - "readout-proxy"
    - "--dangling-outputs-policy"
    - "fairmq"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "{{ tof_proxy_spec }}"
    - "--readers"
    - "1"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"
    - "--end-value-enumeration"
    - "-1"
    - "--session"
    - "default"
    - "--severity"
    - "{{fmq_severity}}"
    - "--shm-monitor false"
