name: stfb-qc-dispatcher
defaults:
  user: flp
  log_task_output: none
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: "from_Dispatcher_to_QC-TASK-RUNNER-dataDistribution"
    type: "push"
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  log: "{{ log_task_output }}"
  shell: true
  value: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load QualityControl Control-OCCPlugin &&
    cat {{dpl_config}}| o2-qc
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--config"
    - "{{qc_config_uri}}"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "Dispatcher"
    - "--log-color"
    - "false"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--period-timer-stats"
    - "10000000"
    - "--severity"
    - "debug"
    - "--shm-monitor false"
    - "--infologger-severity"
    - "{{infologger_severity}}"
    - "--infologger-mode"
    - "{{infologger_mode}}"
