name: stfb-internal-dpl-output-proxy-tof
defaults:
  tof_downstream_spec: "downstream:TOF/CRAWDATA"
  user: flp
  fmq_severity: info
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
connect:
  - name: from_tof-compressor-0_to_internal-dpl-output-proxy
    type: pull
    rateLogging: "60"
  - name: from_tof-compressor-1_to_internal-dpl-output-proxy
    type: pull
    rateLogging: "60"
  - name: from_tof-compressor-2_to_internal-dpl-output-proxy
    type: pull
    rateLogging: "60"
  - name: from_tof-compressor-3_to_internal-dpl-output-proxy
    type: pull
    rateLogging: "60"
bind:
  - name: downstream
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "1"
command:
  shell: true
  value: >-
    eval `aliswmod load O2 Control-OCCPlugin` &&
    cat {{dpl_config}} | o2-dpl-raw-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_tof_url }}"
    - "--id"
    - "internal-dpl-output-proxy"
    - "--dangling-outputs-policy"
    - "fairmq"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "{{ tof_downstream_spec }}"
    - "--readers"
    - "1"
    - "--session"
    - "default"
    - "--severity"
    - "{{fmq_severity}}"
    - "--shm-monitor false"
