name: stfbuilder-nooutput
control:
  mode: fairmq
defaults:
  rdh_version: "6"
wants:
  cpu: 0.15
  memory: 128
command:
  env: []
  shell: true
  user: flp
  value: >-
    eval `aliswmod load DataDistribution Control-OCCPlugin` &&
    StfBuilder
  arguments:
    - "--detector"
    - "TPC"
    - "--verbosity=veryhigh"
    - "--stand-alone"
    - "--detector-rdh"
    - "{{ rdh_version }}"
