name: WalnutChecks
on:
  pull_request:
    paths:
      - 'tasks/*'
      - 'workflows/*'
      - '.github/workflows/template.yml'
  push:
    branches:
      - 'master'

jobs:
  walnut-check:
    name: Check Task and Workflow Templates through Walnut
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
            path: ControlWorkflows
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - uses: actions/checkout@v2
        with: 
          repository: AliceO2Group/Control
          ref: 'master'
          path: Control
      - run: (cd Control; make vendor)
      - run: (cd Control; make)
      - run: (echo "Checks will be ran against branch  ${{ github.ref }}")
      - name: Run Walnut checks for TASKS
        working-directory: ./Control
        run: |
          for file in ./../ControlWorkflows/tasks/*.yaml; do
            echo "Checking file ${file}"
            ./bin/walnut check -f task ${file}
          done
      - name: Run Walnut checks for WORKFLOWS
        working-directory: ./Control
        run: |
            for file in ./../ControlWorkflows/workflows/*.yaml; do
              echo "Checking file ${file}"
              ./bin/walnut check -f workflow ${file}
            done
