name: WalnutChecks
on:
  pull_request:
    paths:
      - 'tasks/*'
      - 'workflows/*'
      - '.github/workflows/template.yml'
  push:
    branches:
      - 'feature/OCTRL-317-add-gh-action-walnut'
      - 'dev'

jobs:
  tasks-check:
    name: Check Tasks Templates through Walnut
    # runs-on: ${{ matrix.os }}
    runs-on: macOS-latest
    # strategy:
    #   matrix:
    #     os: [macOS-latest, ubuntu-18.04]
    #     go: [ '1.14.7', '1.15.0' ]
    steps:
      - uses: actions/checkout@v2
        with:
            path: ControlWorkflows
      - uses: actions/setup-go@v2
        with:
          # go-version: ${{matrix.go}}
          go-version: '1.15.0'
      - uses: actions/checkout@v2
        with: 
          repository: AliceO2Group/Control
          ref: 'master'
          path: Control
      - run: (cd Control; make vendor)
      - run: (cd Control; make)
      - name: Run Walnut checks for TASKS
        working-directory: ./Control
        run: |
          for file in ./../ControlWorkflows/tasks/*.yaml; do
            walnut check -f task ${file}
          done
      - name: Run Walnut checks for WORKFLOWS
        working-directory: ./Control
        run: |
            for file in ./../ControlWorkflows/workflows/*.yaml; do
              walnut check -f workflow ${file}
            done